### ISSUE TITLE
CSS being cut off early (Less, Node, Symfony2)

### ISSUE THREAD

**Issue by aar0nr** [kriswallsmith/assetic#108]
I'm using the Twitter Bootstrap Less CSS:

https://github.com/twitter/bootstrap

Along with:
- symfony v2.0.1
- assetic v1.0.2
- node v0.4.11
- lessc v1.1.3

config.yml

``` yaml
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules]
```

base.html.twig

``` html
{% stylesheets filter='less'
    '@TestAppBundle/Resources/public/css/main.less' %}
    <link rel="stylesheet" href="{{ asset_url }}" type="text/css" media="all" />
{% endstylesheets %}
```

main.less

``` css
// Twitter Bootstrap
@import "bootstrap/bootstrap.less";
```

../bootstrap/bootstrap.less

``` css
/*!
 * Bootstrap v1.1.1
 *
 * Copyright 2011 Twitter, Inc
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Designed and built with all the love in the world @twitter by @mdo and @fat.
 * Date: @DATE
 */
// CSS Reset
@import "reset.less";

// Core
@import "preboot.less";
@import "scaffolding.less";

// Styled patterns and elements
@import "type.less";
@import "forms.less";
@import "tables.less";
@import "patterns.less";
```

It compiles with no errors, but when I view the generated CSS, it cuts off on the last file early.  Any ideas?

../web/app_dev.php/css/1a78627_main_1.css

``` css
...
/* This snippet is from the last file imported: patterns.less */
.modal .modal-footer {
  background-color: #f5f5f5;
  padding: 14px 20px 15px;
  border-top: 1px solid #ddd;
  -webkit-border-radius: 0 0 6px 6px;
  -moz-border-radius: 0 0 6px 6px;
  border-radius: 0 0 6px 6px;
  -webkit-bo
```

A final note... when I run the less compiler manually it outputs the full css with no cutoff:

```
bash$ /usr/local/bin/lessc main.less
```
