### ISSUE TITLE
EnsureFilterWorkers's process is never being called

### ISSUE THREAD

**Issue by klvnptr** [kriswallsmith/assetic#167]
Hi everyone,

I'm using the apply_to param for filters, but it doesn't work. I traced down the error message a bit and all the EnsureFilterWorkers are correctly setup in the container, but the process functions of them are never being called. I used XDebug and PHPStorm and created breakpoints in the construct and process function, thats how I got these facts.

Here is my code from base.html.twig

```
        {%
            javascripts
            '@MyBundle/Resources/public/js/lib/messages_hu.js'
            '@MyBundle/Resources/public/js/bootstrap/bootstrap-modal.js'
            '@MyBundle/Resources/public/js/bootstrap/bootstrap-twipsy.js'
            '@MyBundle/Resources/public/js/bootstrap/bootstrap-dropdown.js'
            '@MyBundle/Resources/public/js/bootstrap/bootstrap-tabs.js'
            '@MyBundle/Resources/public/js/global.coffee'
            filter='coffee'
        %}<script src="{{ asset_url }}"></script>
        {% endjavascripts %}
```

And here is the assetic snippet from my config.yml:

``` yaml
assetic:
    debug:           %kernel.debug%
#    write_to:        "%kernel.root_dir%/../web"
    use_controller:  false

    filters:
        yui_css:
            jar: %kernel.root_dir%/Resources/yui/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/yui/yuicompressor-2.4.6.jar
        coffee:
            bin: /usr/local/bin/coffee
            node: /usr/local/bin/node
            apply_to: "\.coffee$"
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~

    assets:
        all_css:
            inputs:
                - @BotanooBundle/Resources/public/css/app.less
            output: css/all.css
            filters: [less, ?yui_css]

        bootstrap:
            inputs:
                - @MyBundle/Resources/public/js/lib/messages_hu.js
                - @MyBundle/Resources/public/js/bootstrap/bootstrap-modal.js
                - @MyBundle/Resources/public/js/bootstrap/bootstrap-twipsy.js
                - @MyBundle/Resources/public/js/bootstrap/bootstrap-dropdown.js
                - @MyBundle/Resources/public/js/bootstrap/bootstrap-tabs.js

        app_js:
            inputs:
                - @BotanooBundle/Resources/public/js/global.coffee
            filters: [coffee]

        all_js:
            inputs:
                - @bootstrap
                - @app_js
            filters: [?yui_js]
            output: js/all.js
```
