### ISSUE TITLE
Can not find module "less" on windows + assetic hangs

### ISSUE THREAD

**Issue by hellomedia** [kriswallsmith/assetic#185]
Running symfony 2.0.9 on windows 7 with assetic 1.0.x branch ( latest commit b143e360eecf2346a1128eb0630b02ab83c3a3a8 ).
Running into this error with Less filter ( this is the output of the css file ):

``` php
/*
[exception] 500 | Internal Server Error | RuntimeException
[message] 
[1] RuntimeException: 
                at n/a
                    in E:\wamp\www\hellokot\vendor\assetic\src\Assetic\Filter\LessFilter.php line 103

                at Assetic\Filter\LessFilter-&gt;filterLoad(object(Assetic\Asset\FileAsset))
                    in E:\wamp\www\hellokot\vendor\assetic\src\Assetic\Filter\FilterCollection.php line 62

                at Assetic\Filter\FilterCollection-&gt;filterLoad(object(Assetic\Asset\FileAsset))
                    in E:\wamp\www\hellokot\vendor\assetic\src\Assetic\Asset\BaseAsset.php line 83

                at Assetic\Asset\BaseAsset-&gt;doLoad(&#039;/*!
```

I have tried with these branches and get the same error.

lessc-bin ( c274e92b0f46e2d57eb520be5723384a4a0de40e )
inherit-env ( 56cae6720ae1a24650960f2cfc58a8d27f4203a0 )

Trying to catch a more interesting error in assetic/Util/process.php  with

```
die(var_dump($this->status));
```

leads me to this comand

```
"C:\Program Files (x86)\nodejs\node.exe" "C:\Windows\Temp\assFFB0.tmp"
```

Executing this command in the console gets this error

```
Error: Cannot find module 'less'
```

My understanding is that node.js is not given the correct path to less. This is my config.yml

``` yaml
less:
        node: "C:\\Program Files (x86)\\nodejs\\node.exe"
        node_paths: [ "C:\\Program Files (x86)\\nodejs" , "C:\\Program Files (x86)\\nodejs\\node_modules" ]
        apply_to: "\.less$"
```

I am quite stuck, thank you in advance for any hint.
