### ISSUE TITLE
Less variables not imported globaly

### ISSUE THREAD

**Issue by jmeyo** [kriswallsmith/assetic#426]
Currently using the https://github.com/phiamo/symfony-bootstrap, and out of the box, assetic works perfectly but when we update the dependencies, the generated less file throw a 500 exception.

The main differences seems to be the upgrade on this assetic framework, can't figure out if it's related to the symfony assetic bundle.

Initial Git file

``` yml
                "branch-alias": {
                    "dev-master": "1.1-dev"
                }.
```

Updated Git file

``` yml
                "branch-alias": {
                    "dev-master": "1.2-dev"
                }.
```

Stack trace of the exception when loading the file through dev environment
http://somehost/app_dev.php/css/f1e3c9a_mopabootstrapsandboxbundle_1.css

``` php
/*
[exception] 500 | Internal Server Error | Assetic\Exception\FilterException
[message] An error occurred while running:
&#039;/usr/bin/node&#039; &#039;/tmp/assetic_lessDI7bGF&#039;

Error Output:
NameError: variable @inputHeight is undefined in mixins.less:157:14
156   width: 100%;
157   min-height: @inputHeight; // Make inputs at least the height of their button counterpart (base line-height + padding + border)
158   .box-sizing(border-box); // Makes inputs behave like true block-level elements



Input:
//
// Mixins

[truncated}
```
