### ISSUE TITLE
Assetic debug mode in Symfony2 beta1 partly broken

### ISSUE THREAD

**Issue by mgruner** [kriswallsmith/assetic#47]
Hi.
In a small symfony2 project, we just started using assetic.

``` html
        {% stylesheets output="bundles/lt/css/build.css"  '@LTBundle/Resources/public/css/style.css' %}
        <link href="{{ asset_url }}" type="text/css" rel="stylesheet" />
        {% endstylesheets %}
```

This works well in production, generating links like:

``` html
<link href="/lt/bundles/lt/css/build.css" type="text/css" rel="stylesheet" /> 
```

However in dev environment, with the debug flag on (use_controller is still false!), it generates links like:

``` html
<link href="/lt/bundles/lt/css/build_style1.css" type="text/css" rel="stylesheet" /> 
```

But this file is not written by assetic:dump, instead always css/build.css is written like in the prod environment. So in dev environment the css file cannot be found.
Here is the config.yml part for assetic:

``` yaml
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

```

In config_dev.yml, use_controllers was set to false, because otherwise relative image urls will not work any more due to the changed path of the css file (the URL includes the controller, so that the relative images will not be found any more). Do you have a tip for me to make it work also with use_controller: true?

Thanks for considering and for any help. It will be most appreciated.
And thanks for making such a great tool!

Best regards, mg
