### ISSUE TITLE
Bug in regex in CssRewriteFilter

### ISSUE THREAD

**Issue by abretaud** [kriswallsmith/assetic#48]
Hi,
I think there's a mistake in the 2 regex used in CssRewriteFilter (at the end of filterDump).
The problem is that (?<url>.*) allow any character, including ')' which means that if you have several url(foo) in the same css, the matches are wrong. An example:

``` css
foo {
background-image: url(foobar);
padding: whatever;
}
bar {
background-image: url(barfoo);
}
```

with the current regex, you end up matching 

```
foobar);
padding: whatever;
}
bar {
background-image: url(barfoo
```

I corrected it with something like it: '/url((["\']?)(?<url>[^)]*)(\1))/'
The problem should be the same for import regex.
Maybe there's a better solution?
