### ISSUE TITLE
SassFilter - Empty CSS files generated

### ISSUE THREAD

**Issue by gentisaliu** [kriswallsmith/assetic#496]
I am using the SASS filter and after issuing 

``` cmd
php app/console assetic:dump 
```

the dumped CSS files are all empty.

config.yml

``` yaml
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    read_from: '%kernel.root_dir%/../web'
    write_to: '%kernel.root_dir%/../web'
    ruby: '%ruby%'
    java: '%java%'
    filters:
        sass:
          bin: '%sass%'
          apply_to: '\.scss$'
          load_paths:
            - '%kernel.root_dir%/../web/assets'
        cssrewrite: ~
        yui_css:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'
        yui_js:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'
```

config_dev.yml

``` yaml
assetic:
    use_controller: true
```

base.html.haml

``` haml
- stylesheets combine=true filter='cssrewrite,?yui_css' output='assets/css/base.css' |
            'assets/bundles/ictsamticoreassets/css/base/base.scss' |
            %link(href=asset_url type="text/css" rel="stylesheet")

- stylesheets combine=true filter='cssrewrite,?yui_css' output='assets/css/frontend.css' |
        'assets/bundles/ictsamticoreassets/css/frontend/main.scss' |
        %link(href=asset_url type="text/css" rel="stylesheet")
```

The first stylesheet (base.css) seems to compile fine, however the other (frontend.css) is empty.

I am running on a Windows 7 SP1 64-bit machine with PHP version 5.4.19, Ruby 2.0.0 (64 bit) and sass v3.2.10.

I suspect it has something to do with reading the output of the compile command from the file pipe (in proc_open), which for some reason is empty. 
Running the SASS compilation commands outputs the CSS code I expect, so that shouldn't be the problem.

I also stumbled upon this issue (https://github.com/kriswallsmith/assetic/issues/99), and tried setting the $env parameter to null, but to no avail.

The compilation with Assetic runs fine in another Debian machine.

Probably this is a PHP bug (https://bugs.php.net/bug.php?id=50503, referenced in the issue above), but I'd love to know whether there is another way to fix this. I have been struggling with this (ridiculous) issue for 2 days and it's keeping me from doing the real work, so it would be fantastic if a fix were to be found.

Thanks.
