### ISSUE TITLE
Cache busting with variables not working

### ISSUE THREAD

**Issue by Lumbendil** [kriswallsmith/assetic#571]
When enabling cache busting and having an asset which it's input depend on a variable, makes some assets disappear.

**Comment by mekras** [comment]
I think we have the same issue using assetic with Symfony.
Config:
```yaml
assetic:
    variables:
        locale: [de, en, ru]
    workers:
        cache_busting: ~
```
Template:
```twig
{% image 'path/{locale}/image.png' vars=['locale'] %}
<img src="{{ asset_url }}">
{% endimage %}
```
assetic:dump command fails with error:

```
[InvalidArgumentException] 
The template "../web/path/{locale}/image.png" contains the variable "locale", but was not given any value for it.
```
This happens because workers are applied before AssetCollection::setValues is called.
