### ISSUE TITLE
SassFilter --debug-info flag references temp file, not originating sass file

### ISSUE THREAD

**Issue by stratease** [kriswallsmith/assetic#623]
There appears to be an issue with various sass to css file mapping tools such as Fire Compass in Firefox. It is referencing a temp file instead of the originating sass file. Below you can see the section of code I'm referencing.

https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Filter/Sass/SassFilter.php#L163

``` php
...
$pb->add($input = tempnam(sys_get_temp_dir(), 'assetic_sass'));
file_put_contents($input, $asset->getContent());

```

And this is a snippet of the debug info that is output in the css.

``` css
...
@media -sass-debug-info {
filename {
    font-family: file:///tmp/assetic_sassIvzIp9;
}
```

This appears to be because the sass file is copied to a temp file, then compiled off that.

Is this by design?
