### ISSUE TITLE
Console application

### ISSUE THREAD

**Issue by Kilte** [kriswallsmith/assetic#670]
What do you think about standalone console application?

For example, we have a configuration file for assetic &mdash; `assetic.yml`:

```yaml
assets:
  source:
    - web/app.js
    - web/vendor/*.js
  dest: web/build.js
```

Then we can run `php assetic.phar dump` and get `web/build.js`.

I have tried to find something ready-made, but nothing found.
