### ISSUE TITLE
Sprites not working inside media queries

### ISSUE THREAD

**Issue by ScienceofSpock** [kriswallsmith/assetic#676]
I have a spritesheet being generated, and it works well, except when it's used inside media query breakpoints. I recently discovered that our page logo was too large for the smallest phone size we wanted to support, so I decided to throw a breakpoint to change the size, position and background image for widths smaller than 400px:

``` css
.site-logo {
  width: 250px;
  height: 38px;
  margin: 20px auto 0px auto;
  @extend .icons-logo-site-med;
  @media screen and (max-width: $break-phone-tiny) {
    width: 200px;
    height: 30px;
    margin: 20px auto 0px auto;
    @extend .icons-logo-site-small;
  }
}
```

The logo shows up normally, except when the site is reduced to a width less than $break-phone-tiny, at which point, the logo dimensions change properly, but the background image stays the same, effectively cropping the logo. Examining the element shows that the background-image property getting generated inside the media query is getting overridden by the base class, so it's just using the base background-image. I can correct this by just specifying the correct background-position inside the media query, but I feel that the automated sprite generation may not put the same sprites in the same place in the sprite sheet, especially if new sprites are introduced, breaking the logo image.

This is the CSS that's getting generated:

``` css
.site-logo{
    width:250px;
    height:38px;
    margin:20px auto 0px auto;
    background:url('/images/sprite/icons-s94c91f32d7.png') no-repeat;
    background-position:0 -70px;
}
@media screen and (max-width: 400px){
    .site-logo{
        width:200px;
        height:30px;
        margin:20px auto 0px auto
    }
}
```

How do I get the sprites to work inside media queries?
