### ISSUE TITLE
1.1.3 update breaks less compiled styles

### ISSUE THREAD

**Issue by matheo** [kriswallsmith/assetic#688]
After today's `composer update` the styles got broken.
Seems that my `.less` files are no longer compiled :(
I'm a symfony 2 developer using the AsseticBundle, which relies on `1.1.*`
forcing my project to use the `1.1.2` fixes the styles again.

**Comment by isometriks** [comment]
@kriswallsmith Took me a while to figure out exactly what was causing it but I think I've found it. When you create an asset with multiple inputs and all of the inputs aren't of the same type this problem occurs:

```yml
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    assets:
        some_asset:
            inputs:
                - @AppBundle/Resources/test.css
                - @AppBundle/Resources/test1.less
                - @AppBundle/Resources/test2.less
```

If you remove the test.css then the other less files compile just fine. Previous to the AssetReference modification this did work. I did make a project just in case, but you should be able to replicate with a simple config as above: https://github.com/isometriks/AsseticTestProject

I was originally doing this through my own forumula loader/resource but the same happens through the config. 

I'll try to look into it further.

**Comment by isometriks** [comment]
@kriswallsmith still having some trouble here. I've tried a few different things to fix this but I know they aren't the "right" way to do it. As I had mentioned, I can remove the "clone $asset" part from AssetReference, and I've also found that changing AssetCollection's clone to $this->clones = clone $this->clones, or removing that line altogether works. I fixed my project as before it had an error in the composer.json but it still produces the same issue. If you git clone https://github.com/isometriks/AsseticTestProject install vendors, and then run `php app/console assetic:dump --env=prod` you'll be left with a css file that looks something like this:

```less
body {
    line-height: 30px;
}

body {
    p {
        background-color: red;
    }
}
body {
    p {
        font-family: 'Comic Sans MS';
    }
}
```
