### ISSUE TITLE
uglifycss under Windows throws exception

### ISSUE THREAD

**Issue by Alumbrados** [kriswallsmith/assetic#717]
The folowing config generates an exception on css files that apply the uglifycss filter.

```
assetic:
    node: "C:/Program Files/nodejs/node.exe"
    ...
    filters:
        uglifycss:
            bin: "C:/Users/Martijn/AppData/Roaming/npm/uglifycss"
        ...
```

```
[exception] 500 | Internal Server Error | Assetic\Exception\FilterException
[message] An error occurred while running:
"C:/Program Files/nodejs/node.exe" "C:/Users/Martijn/AppData/Roaming/npm/uglifycss" "C:\Windows\Temp\inp3B91.tmp"

Error Output:
C:\Users\Martijn\AppData\Roaming\npm\uglifycss:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I'm probably missing something important but I think the config assumes I'm on Linux.
