### ISSUE TITLE
Assetic doesn't re-generate asset if a named asset it includes is changed

### ISSUE THREAD

**Issue by bkosborne** [kriswallsmith/assetic#726]
I named a named asset `bootstrap_css`:

```
assetic:
    ...
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
            output: css/bootstrap.css
```

In my twig template, I have the following:
```
{% stylesheets
'@bootstrap_css'
'css/styles.css'
output='compiled/css/app.css'
%}
    <link rel="stylesheet" href="{{ asset_url }}" />
{% endstylesheets %}
```

So, I'm combining the bootstrap CSS with my app's main CSS file.

When I make changes to a bootstrap less file, then assetic will re-compile the `bootstrap.css` file as expected. However, it will NOT re-compile the combined `app.css` file, even though it depends on `bootstrap.css`.

I have to make a change to style.css to trigger assetic to update` app.css`, which will then also pick up the changes `bootstrap.css` file.

Is this a known issue? Maybe something I'm overlooking?
