### ISSUE TITLE
Problem in comment regex match

### ISSUE THREAD

**Issue by ockcyp** [kriswallsmith/assetic#758]
```scss
@import "sprites/*.png";

/* some comment */
.this-class {
    background-color: #666;
}
```
``Assetic\Util\CssUtils::filterCommentless()`` returns:
```scss
@import "sprites
.this-class {
    background-color: #666;
}
```

``Assetic\Util\CssUtils::filterCommentless()`` should ignore comment start (``/*``) if it is inside a string
