### ISSUE TITLE
"cssrewrite" filter not found in Symfony 3

### ISSUE THREAD

**Issue by aimeos** [kriswallsmith/assetic#781]
We use a Twig template that contains the following code:

```
    {% stylesheets
        'bundles/aimeosshop/themes/elegance/common.css'
        'bundles/aimeosshop/themes/elegance/aimeos.css'
        filter='cssrewrite'
    %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
```

For Symfony 3 this fails with an exception "There is no "cssrewrite" filter." while it works for Symfony 2. The assetic bundle is registered in ./app/AppKernel.php with `new Symfony\Bundle\AsseticBundle\AsseticBundle()`.

What causes this problem?

**Comment by andrewtch** [comment]
Works as per latest sass bundle, please update or close )

**Comment by enrique-ibarra** [comment]
On my case, I had a similar issue and the problem was the missing configuration in app/config/config.yml

```yaml
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
```

Once `cssrewrite` is added to the list of filters, the problem is solved for me.
