### ISSUE TITLE
mtime regression

### ISSUE THREAD

**Issue by lenar** [kriswallsmith/assetic#82]
I have following configuration in symfony:

```
assetic:
    filters:
        scss:
            apply_to: "\.scss$"
        cssrewrite:
            apply_to: "\.css$"
```

Before commit "mtime-aware" 50d19c4af63a3216e014 it worked. 4fffe721606a46712d61 works.
But now the scss filter is not applied anymore.
