### ISSUE TITLE
Assetic and yui_css generating empty files

### ISSUE THREAD

**Issue by ajfranzoia** [kriswallsmith/assetic#99]
Hi. I'm using Assetic with yui_css and I'm having some trouble.

Assetic ver.: 1.0.1 (Commit: 3e457819c9cb04018a7f  - aug 10)
yuicompressor ver: 2.4.6

config.yml

``` yaml
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
```

config_dev.yml

``` yaml
assetic:
    use_controller: true
```

base.html.twig

``` html
{% stylesheets 'bundles/miapp/css/layout.css' filter='yui_css' %}
    <link href="{{ asset_url }}" type="text/css" rel="stylesheet" />
{% endstylesheets %}
```

The generated css ("XXXXXX_layout_1.css") is fetched OK by the browser, but it is empty. The file generated under web/css is empty as well. 
Proccessing the css wfile ith "java -jar yuicompressor layout.css" produces the right result.

Am I missing any configuration?
